name: Trash-Bank
services:
  apache2-composer-maria-pma:
    container_name: apache2
    build:
      context: .docker
      dockerfile: Dockerfile
    # image: php:8.1-apache
    depends_on:
      - database
    volumes:
      - ./App:/var/www/html
      - ./.docker/httpd.conf:/etc/apache2/httpd.conf
    ports:
      - 8000:80
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    command: apache2-foreground
  ################################################
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: trash_bank
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9906:3306"
  ################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database
  ###############################################
  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "8443:443"
      - "8081:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/certs:/etc/nginx/certs
    depends_on:
      - apache2-composer-maria-pma
