name: waste-bank
services:
  apache2:
    container_name:  waste_bank_app
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./App:/var/www/html
      - ./.docker/httpd.conf:/etc/apache2/httpd.conf
    env_file:
      - .env
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    command: apache2-foreground
    depends_on:
      - database
  ################################################
  database:
    container_name: database
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9906:3306"
  ################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database
